services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "app:app", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-", "--reload"]

  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app