name: Deploy Backend

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_SERVICE_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev
          docker build -t northamerica-northeast2-docker.pkg.dev/sunny-airfoil-454023-h3/gcpdiagramgenerator/backend:latest ./backend
          docker push northamerica-northeast2-docker.pkg.dev/sunny-airfoil-454023-h3/gcpdiagramgenerator/backend:latest
